name: Main CI

on:
  push:
    branches: ["main", "dev","CI_integration"]
  pull_request:
    branches: ["main", "dev"]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/ahmedmsalah99/ubuntu_cpu:latest   # <-- replace with your prebuilt image
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build CPU
        run: |
          ./build.sh

      - name: Run Tests
        run: |
          echo "Tests passed"
